# Generated by Django 4.2.6 on 2023-10-16 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('choice', models.CharField(max_length=100)),
                ('total_votes', models.PositiveIntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Choices',
                'ordering': ['total_votes'],
            },
        ),
        migrations.CreateModel(
            name='VotersDetails',
            fields=[
                ('id', models.CharField(editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('selected_choice', models.CharField(editable=False, max_length=100)),
                ('voting_date', models.DateTimeField(auto_now_add=True)),
                ('polls', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='polls.choices')),
                ('voter', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Voters Logs',
                'ordering': ['polls', '-voting_date'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('quiz', models.TextField()),
                ('category', models.CharField(max_length=15)),
                ('is_private', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False, editable=False)),
                ('closing_dt', models.DateField(db_column='Scheduled closing date-time')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='choices',
            name='question',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='polls.questions'),
        ),
    ]
